apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lj701-3-x-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:df74f2a673b58b6c5f0bc393833ec27dbeeda12e@sha256:b26f9b99e88653dcf8efd5f568ecd7d8eb35d0d770446d91ab3ae152d7c22c30
          name: container-image
